In [6]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('pima-indians-diabetes.csv', header = None)

In [8]:
df.head()

   0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [9]:
df.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [10]:
df.columns = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']

In [11]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [12]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [13]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [14]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [16]:
X_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [17]:
X_scaled.shape

(768, 8)

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size = 0.2,random_state = 1)

In [51]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [20]:
model = Sequential()
model.add(Dense(32,activation = 'relu', input_dim = 8))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'Adam', loss = 'binary_crossentropy',metrics = ['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
history = model.fit(X_train,y_train,batch_size = 32, epochs = 100, validation_data = (X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6401 - loss: 0.6495 - val_accuracy: 0.6623 - val_loss: 0.6448
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7215 - loss: 0.5970 - val_accuracy: 0.6883 - val_loss: 0.5986
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5627 - val_accuracy: 0.7338 - val_loss: 0.5670
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7508 - loss: 0.5391 - val_accuracy: 0.7727 - val_loss: 0.5454
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5210 - val_accuracy: 0.7727 - val_loss: 0.5266
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5073 - val_accuracy: 0.7727 - val_loss: 0.5139
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4982 - val_accuracy: 0.7662 - val_loss: 0.5048
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4907 - val_accuracy: 0.7792 - val_loss: 0.4969
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4854 - val_accuracy: 0.7792 - val_loss: 0.4922
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4801 - val_accuracy: 0.7792 - val_loss: 0.4869
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4759 - val_accuracy: 0.7727 - val_loss: 0.4835
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4719 - val_accuracy: 0.7792 - val_loss: 0.4816
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4689 - val_accuracy: 0.7857 - val_loss: 0.4806
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4662 - val_accuracy: 0.7857 - val_loss: 0.4795
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4640 - val_accuracy: 0.7857 - val_loss: 0.4768
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4622 - val_accuracy: 0.7792 - val_loss: 0.4755
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4600 - val_accuracy: 0.7857 - val_loss: 0.4734
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4582 - val_accuracy: 0.7857 - val_loss: 0.4732
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4573 - val_accuracy: 0.7792 - val_loss: 0.4711
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4556 - val_accuracy: 0.7792 - val_loss: 0.4704
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4541 - val_accuracy: 0.7727 - val_loss: 0.4694
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4531 - val_accuracy: 0.7727 - val_loss: 0.4691
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4522 - val_accuracy: 0.7857 - val_loss: 0.4681
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4510 - val_accuracy: 0.7857 - val_loss: 0.4681
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4502 - val_accuracy: 0.7857 - val_loss: 0.4678
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4495 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4480 - val_accuracy: 0.7857 - val_loss: 0.4688
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4469 - val_accuracy: 0.7987 - val_loss: 0.4682
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4464 - val_accuracy: 0.7922 - val_loss: 0.4674
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4461 - val_accuracy: 0.7922 - val_loss: 0.4698
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4447 - val_accuracy: 0.7922 - val_loss: 0.4684
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4442 - val_accuracy: 0.7987 - val_loss: 0.4680
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4429 - val_accuracy: 0.7987 - val_loss: 0.4670
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4425 - val_accuracy: 0.7987 - val_loss: 0.4667
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4420 - val_accuracy: 0.7922 - val_loss: 0.4667
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4413 - val_accuracy: 0.7987 - val_loss: 0.4651
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4409 - val_accuracy: 0.8052 - val_loss: 0.4656
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4400 - val_accuracy: 0.7987 - val_loss: 0.4665
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4395 - val_accuracy: 0.7987 - val_loss: 0.4670
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4392 - val_accuracy: 0.7987 - val_loss: 0.4672
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4390 - val_accuracy: 0.7922 - val_loss: 0.4670
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4373 - val_accuracy: 0.7987 - val_loss: 0.4678
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4372 - val_accuracy: 0.7987 - val_loss: 0.4685
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4368 - val_accuracy: 0.8052 - val_loss: 0.4668
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4365 - val_accuracy: 0.8052 - val_loss: 0.4670
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4357 - val_accuracy: 0.7987 - val_loss: 0.4665
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4355 - val_accuracy: 0.7987 - val_loss: 0.4658
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4345 - val_accuracy: 0.7987 - val_loss: 0.4670
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4334 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4337 - val_accuracy: 0.7987 - val_loss: 0.4672
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4327 - val_accuracy: 0.7987 - val_loss: 0.4669
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4323 - val_accuracy: 0.7987 - val_loss: 0.4665
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4318 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4315 - val_accuracy: 0.8052 - val_loss: 0.4684
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4306 - val_accuracy: 0.8052 - val_loss: 0.4681
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4302 - val_accuracy: 0.8052 - val_loss: 0.4677
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4300 - val_accuracy: 0.7857 - val_loss: 0.4667
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4294 - val_accuracy: 0.7857 - val_loss: 0.4668
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4297 - val_accuracy: 0.7857 - val_loss: 0.4684
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4284 - val_accuracy: 0.7922 - val_loss: 0.4673
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4277 - val_accuracy: 0.7922 - val_loss: 0.4671
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4279 - val_accuracy: 0.7857 - val_loss: 0.4672
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4276 - val_accuracy: 0.7857 - val_loss: 0.4681
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4270 - val_accuracy: 0.7857 - val_loss: 0.4691
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4265 - val_accuracy: 0.7922 - val_loss: 0.4688
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4265 - val_accuracy: 0.7857 - val_loss: 0.4691
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4256 - val_accuracy: 0.7857 - val_loss: 0.4694
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4255 - val_accuracy: 0.7922 - val_loss: 0.4695
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4242 - val_accuracy: 0.7922 - val_loss: 0.4671
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4245 - val_accuracy: 0.7922 - val_loss: 0.4671
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4244 - val_accuracy: 0.7857 - val_loss: 0.4652
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4234 - val_accuracy: 0.7857 - val_loss: 0.4662
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4228 - val_accuracy: 0.7857 - val_loss: 0.4669
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4225 - val_accuracy: 0.7857 - val_loss: 0.4665
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4224 - val_accuracy: 0.7857 - val_loss: 0.4674
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4217 - val_accuracy: 0.7857 - val_loss: 0.4677
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4214 - val_accuracy: 0.7922 - val_loss: 0.4660
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4213 - val_accuracy: 0.7922 - val_loss: 0.4660
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4207 - val_accuracy: 0.7857 - val_loss: 0.4658
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4205 - val_accuracy: 0.7857 - val_loss: 0.4651
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4203 - val_accuracy: 0.7857 - val_loss: 0.4649
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4198 - val_accuracy: 0.7857 - val_loss: 0.4651
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7899 - loss: 0.4193 - val_accuracy: 0.7922 - val_loss: 0.4650
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7964 - loss: 0.4193 - val_accuracy: 0.7857 - val_loss: 0.4635
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4189 - val_accuracy: 0.7857 - val_loss: 0.4647
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4185 - val_accuracy: 0.7857 - val_loss: 0.4641
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4181 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4176 - val_accuracy: 0.7922 - val_loss: 0.4638
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4176 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4173 - val_accuracy: 0.7922 - val_loss: 0.4632
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4170 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4172 - val_accuracy: 0.7987 - val_loss: 0.4659
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4169 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4160 - val_accuracy: 0.7922 - val_loss: 0.4637
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4157 - val_accuracy: 0.7922 - val_loss: 0.4638
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4163 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4153 - val_accuracy: 0.7922 - val_loss: 0.4642
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4158 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4149 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4138 - val_accuracy: 0.7922 - val_loss: 0.4656

In [22]:
# 1. How to select appropriate optimizer
# 2. How to select no. of nodes in a layer
# 3. How to select no. of hidden layers

In [23]:
!pip install -q keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.9 MB/s eta 0:00:00

In [24]:
import kerastuner as kt

/tmp/ipykernel_537/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [25]:
def build_model(hp):

  model = Sequential()

  model.add(Dense(32,activation = 'relu', input_dim = 8))
  model.add(Dense(1,activation = 'sigmoid'))


  optimizers = hp.Choice('optimizer', values = ['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer = optimizers, loss = 'binary_crossentropy',metrics = ['accuracy'])

  return model

In [26]:
tuner = kt.RandomSearch(build_model,objective = 'val_accuracy',max_trials = 5)

In [27]:
tuner.search(X_train,y_train,epochs = 5, validation_data = (X_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7662337422370911

Best val_accuracy So Far: 0.7662337422370911
Total elapsed time: 00h 00m 18s

In [28]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [29]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [30]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.fit(X_train,y_train,batch_size = 32,epochs = 100, initial_epoch = 5,validation_data = (X_test,y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7345 - loss: 0.5810 - val_accuracy: 0.7597 - val_loss: 0.5494
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5488 - val_accuracy: 0.7662 - val_loss: 0.5248
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7638 - loss: 0.5275 - val_accuracy: 0.7922 - val_loss: 0.5079
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7622 - loss: 0.5114 - val_accuracy: 0.7792 - val_loss: 0.4952
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4986 - val_accuracy: 0.7727 - val_loss: 0.4874
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4904 - val_accuracy: 0.7792 - val_loss: 0.4823
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4844 - val_accuracy: 0.7792 - val_loss: 0.4777
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4782 - val_accuracy: 0.7857 - val_loss: 0.4734
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4742 - val_accuracy: 0.7792 - val_loss: 0.4703
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7769 - loss: 0.4704 - val_accuracy: 0.7922 - val_loss: 0.4697
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7720 - loss: 0.4679 - val_accuracy: 0.7987 - val_loss: 0.4688
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7785 - loss: 0.4653 - val_accuracy: 0.7987 - val_loss: 0.4692
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7752 - loss: 0.4633 - val_accuracy: 0.8052 - val_loss: 0.4682
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7769 - loss: 0.4616 - val_accuracy: 0.7987 - val_loss: 0.4678
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7752 - loss: 0.4609 - val_accuracy: 0.7922 - val_loss: 0.4673
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7818 - loss: 0.4590 - val_accuracy: 0.7987 - val_loss: 0.4661
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7769 - loss: 0.4572 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7785 - loss: 0.4566 - val_accuracy: 0.7987 - val_loss: 0.4683
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7818 - loss: 0.4552 - val_accuracy: 0.7987 - val_loss: 0.4664
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7801 - loss: 0.4542 - val_accuracy: 0.7987 - val_loss: 0.4666
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7785 - loss: 0.4530 - val_accuracy: 0.7922 - val_loss: 0.4657
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7801 - loss: 0.4525 - val_accuracy: 0.7922 - val_loss: 0.4658
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7834 - loss: 0.4514 - val_accuracy: 0.7922 - val_loss: 0.4665
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4510 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7834 - loss: 0.4500 - val_accuracy: 0.7922 - val_loss: 0.4667
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7834 - loss: 0.4490 - val_accuracy: 0.7922 - val_loss: 0.4672
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7769 - loss: 0.4485 - val_accuracy: 0.7922 - val_loss: 0.4672
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7785 - loss: 0.4479 - val_accuracy: 0.7922 - val_loss: 0.4664
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7801 - loss: 0.4474 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7752 - loss: 0.4461 - val_accuracy: 0.7922 - val_loss: 0.4678
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7769 - loss: 0.4457 - val_accuracy: 0.7922 - val_loss: 0.4676
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7736 - loss: 0.4450 - val_accuracy: 0.7922 - val_loss: 0.4649
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7752 - loss: 0.4446 - val_accuracy: 0.7987 - val_loss: 0.4646
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7785 - loss: 0.4439 - val_accuracy: 0.7922 - val_loss: 0.4655
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4430 - val_accuracy: 0.7922 - val_loss: 0.4650
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7785 - loss: 0.4429 - val_accuracy: 0.7987 - val_loss: 0.4655
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4419 - val_accuracy: 0.7987 - val_loss: 0.4644
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7883 - loss: 0.4415 - val_accuracy: 0.7987 - val_loss: 0.4652
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7899 - loss: 0.4409 - val_accuracy: 0.7987 - val_loss: 0.4652
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4400 - val_accuracy: 0.7987 - val_loss: 0.4645
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4396 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4388 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4386 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4386 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4379 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4371 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4370 - val_accuracy: 0.7987 - val_loss: 0.4639
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4368 - val_accuracy: 0.7987 - val_loss: 0.4639
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4361 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4357 - val_accuracy: 0.7987 - val_loss: 0.4630
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4345 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4344 - val_accuracy: 0.7987 - val_loss: 0.4619
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4344 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4341 - val_accuracy: 0.7987 - val_loss: 0.4638
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4328 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4325 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4326 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4316 - val_accuracy: 0.7987 - val_loss: 0.4648
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4314 - val_accuracy: 0.7987 - val_loss: 0.4657
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4305 - val_accuracy: 0.7922 - val_loss: 0.4684
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4313 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7997 - loss: 0.4321 - val_accuracy: 0.7922 - val_loss: 0.4668
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4307 - val_accuracy: 0.7987 - val_loss: 0.4643
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4297 - val_accuracy: 0.7987 - val_loss: 0.4644
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4290 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7866 - loss: 0.4286 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7899 - loss: 0.4281 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7948 - loss: 0.4280 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4280 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4277 - val_accuracy: 0.8052 - val_loss: 0.4615
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4272 - val_accuracy: 0.8052 - val_loss: 0.4626
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4266 - val_accuracy: 0.8052 - val_loss: 0.4628
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4263 - val_accuracy: 0.8052 - val_loss: 0.4622
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4263 - val_accuracy: 0.8052 - val_loss: 0.4637
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4257 - val_accuracy: 0.7987 - val_loss: 0.4634
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4260 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4250 - val_accuracy: 0.7987 - val_loss: 0.4620
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4242 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4244 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4241 - val_accuracy: 0.8052 - val_loss: 0.4623
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4238 - val_accuracy: 0.7987 - val_loss: 0.4624
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4235 - val_accuracy: 0.7987 - val_loss: 0.4607
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4234 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.8117 - val_loss: 0.4624
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4224 - val_accuracy: 0.8117 - val_loss: 0.4616
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4220 - val_accuracy: 0.8182 - val_loss: 0.4617
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4216 - val_accuracy: 0.8182 - val_loss: 0.4623
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4216 - val_accuracy: 0.8052 - val_loss: 0.4622
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4213 - val_accuracy: 0.8117 - val_loss: 0.4616
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4208 - val_accuracy: 0.8117 - val_loss: 0.4627
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4211 - val_accuracy: 0.8052 - val_loss: 0.4627
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4203 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4198 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4199 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4192 - val_accuracy: 0.8052 - val_loss: 0.4630

In [32]:
def build_model(hp):

  model = Sequential()

  units = hp.Int('units',min_value = 8,max_value = 128)

  model.add(Dense(units = units,activation = 'relu',input_dim = 8))
  model.add(Dense(1,activation = 'sigmoid'))

  model.compile(optimizer ='rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

  return model

In [33]:
tuner = kt.RandomSearch(build_model,objective = 'val_accuracy', max_trials = 5,directory = 'dir',project_name = 'project2')

In [34]:
tuner.search(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 11s

In [35]:
tuner.get_best_hyperparameters()[0].values

{'units': 110}

In [36]:
model = tuner.get_best_models(num_models =1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [37]:
model.fit(X_train,y_train,batch_size = 32,epochs = 100,initial_epoch = 5,validation_data = (X_test,y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7459 - loss: 0.5021 - val_accuracy: 0.8052 - val_loss: 0.4745
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4818 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4715 - val_accuracy: 0.7987 - val_loss: 0.4568
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4641 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4590 - val_accuracy: 0.8117 - val_loss: 0.4521
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4562 - val_accuracy: 0.8052 - val_loss: 0.4513
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4532 - val_accuracy: 0.8052 - val_loss: 0.4505
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4502 - val_accuracy: 0.8052 - val_loss: 0.4484
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4491 - val_accuracy: 0.8052 - val_loss: 0.4502
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4465 - val_accuracy: 0.8117 - val_loss: 0.4491
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4458 - val_accuracy: 0.8052 - val_loss: 0.4496
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4433 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4427 - val_accuracy: 0.7987 - val_loss: 0.4499
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4428 - val_accuracy: 0.8052 - val_loss: 0.4505
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4404 - val_accuracy: 0.8117 - val_loss: 0.4494
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4394 - val_accuracy: 0.8117 - val_loss: 0.4494
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4386 - val_accuracy: 0.8052 - val_loss: 0.4525
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4372 - val_accuracy: 0.8117 - val_loss: 0.4509
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4360 - val_accuracy: 0.8117 - val_loss: 0.4521
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4352 - val_accuracy: 0.8117 - val_loss: 0.4505
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4350 - val_accuracy: 0.8182 - val_loss: 0.4500
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4344 - val_accuracy: 0.8182 - val_loss: 0.4501
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4330 - val_accuracy: 0.8117 - val_loss: 0.4532
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4324 - val_accuracy: 0.7987 - val_loss: 0.4515
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4318 - val_accuracy: 0.8117 - val_loss: 0.4525
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4310 - val_accuracy: 0.8117 - val_loss: 0.4519
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4299 - val_accuracy: 0.8182 - val_loss: 0.4493
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4294 - val_accuracy: 0.8117 - val_loss: 0.4510
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4285 - val_accuracy: 0.8117 - val_loss: 0.4534
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4279 - val_accuracy: 0.8117 - val_loss: 0.4531
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4280 - val_accuracy: 0.8117 - val_loss: 0.4515
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4264 - val_accuracy: 0.8117 - val_loss: 0.4526
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4259 - val_accuracy: 0.8117 - val_loss: 0.4523
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4250 - val_accuracy: 0.8117 - val_loss: 0.4521
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4239 - val_accuracy: 0.7987 - val_loss: 0.4533
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4238 - val_accuracy: 0.7987 - val_loss: 0.4550
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4227 - val_accuracy: 0.8052 - val_loss: 0.4538
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4224 - val_accuracy: 0.8052 - val_loss: 0.4543
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4214 - val_accuracy: 0.8052 - val_loss: 0.4545
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4218 - val_accuracy: 0.8052 - val_loss: 0.4536
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4207 - val_accuracy: 0.7922 - val_loss: 0.4550
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4201 - val_accuracy: 0.8247 - val_loss: 0.4526
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4187 - val_accuracy: 0.8052 - val_loss: 0.4527
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4190 - val_accuracy: 0.8182 - val_loss: 0.4536
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4185 - val_accuracy: 0.8117 - val_loss: 0.4529
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4179 - val_accuracy: 0.8117 - val_loss: 0.4524
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4165 - val_accuracy: 0.8052 - val_loss: 0.4525
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4169 - val_accuracy: 0.8182 - val_loss: 0.4536
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4162 - val_accuracy: 0.8052 - val_loss: 0.4538
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4157 - val_accuracy: 0.8052 - val_loss: 0.4559
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4153 - val_accuracy: 0.8182 - val_loss: 0.4551
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4140 - val_accuracy: 0.8182 - val_loss: 0.4551
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4135 - val_accuracy: 0.8117 - val_loss: 0.4556
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.4136 - val_accuracy: 0.8117 - val_loss: 0.4555
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.4126 - val_accuracy: 0.8182 - val_loss: 0.4552
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8062 - loss: 0.4117 - val_accuracy: 0.8117 - val_loss: 0.4553
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.4111 - val_accuracy: 0.8182 - val_loss: 0.4531
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.4107 - val_accuracy: 0.8117 - val_loss: 0.4543
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8062 - loss: 0.4105 - val_accuracy: 0.8117 - val_loss: 0.4537
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8062 - loss: 0.4110 - val_accuracy: 0.8117 - val_loss: 0.4546
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8094 - loss: 0.4090 - val_accuracy: 0.8182 - val_loss: 0.4531
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8176 - loss: 0.4091 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8127 - loss: 0.4086 - val_accuracy: 0.8182 - val_loss: 0.4528
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.4087 - val_accuracy: 0.8182 - val_loss: 0.4529
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.4079 - val_accuracy: 0.8247 - val_loss: 0.4549
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8274 - loss: 0.4072 - val_accuracy: 0.8182 - val_loss: 0.4566
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4062 - val_accuracy: 0.8117 - val_loss: 0.4553
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4062 - val_accuracy: 0.8182 - val_loss: 0.4562
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4056 - val_accuracy: 0.8117 - val_loss: 0.4577
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4043 - val_accuracy: 0.8117 - val_loss: 0.4587
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4047 - val_accuracy: 0.8117 - val_loss: 0.4562
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4054 - val_accuracy: 0.8117 - val_loss: 0.4578
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4036 - val_accuracy: 0.8182 - val_loss: 0.4599
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4031 - val_accuracy: 0.8182 - val_loss: 0.4569
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.4031 - val_accuracy: 0.8247 - val_loss: 0.4574
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4017 - val_accuracy: 0.8117 - val_loss: 0.4576
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4025 - val_accuracy: 0.8182 - val_loss: 0.4562
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4024 - val_accuracy: 0.8117 - val_loss: 0.4562
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4003 - val_accuracy: 0.8117 - val_loss: 0.4594
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.4005 - val_accuracy: 0.8117 - val_loss: 0.4590
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3996 - val_accuracy: 0.8117 - val_loss: 0.4587
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.4005 - val_accuracy: 0.8247 - val_loss: 0.4582
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3995 - val_accuracy: 0.8182 - val_loss: 0.4575
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3988 - val_accuracy: 0.8117 - val_loss: 0.4596
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3978 - val_accuracy: 0.8182 - val_loss: 0.4577
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3980 - val_accuracy: 0.8182 - val_loss: 0.4590
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3978 - val_accuracy: 0.8117 - val_loss: 0.4590
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3966 - val_accuracy: 0.8117 - val_loss: 0.4569
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3970 - val_accuracy: 0.8182 - val_loss: 0.4592
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3960 - val_accuracy: 0.8182 - val_loss: 0.4599
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3963 - val_accuracy: 0.8052 - val_loss: 0.4610
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3949 - val_accuracy: 0.8117 - val_loss: 0.4601
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3950 - val_accuracy: 0.8182 - val_loss: 0.4595
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3953 - val_accuracy: 0.8117 - val_loss: 0.4608
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3936 - val_accuracy: 0.8117 - val_loss: 0.4601

In [38]:
def build_model(hp):

  model = Sequential()
  model.add(Dense(72,activation = 'relu', input_dim = 8))

  for i in range(hp.Int('num_layers',min_value = 1, max_value = 10)):
    model.add(Dense(72,activation = 'relu'))

  model.add(Dense(1,activation = 'sigmoid'))

  model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

  return model

In [39]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy',max_trials = 5,directory = 'mydir', project_name = 'num_layers')

In [40]:
tuner.search(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.8116883039474487

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 15s

In [41]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2}

In [42]:
model = tuner.get_best_models(num_models =1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [43]:
model.fit(X_train,y_train,batch_size =32,epochs = 100,initial_epoch = 6,validation_data = (X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7736 - loss: 0.4564 - val_accuracy: 0.8117 - val_loss: 0.4725
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4443 - val_accuracy: 0.7922 - val_loss: 0.4773
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4359 - val_accuracy: 0.7922 - val_loss: 0.4863
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4371 - val_accuracy: 0.8117 - val_loss: 0.4658
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4285 - val_accuracy: 0.7987 - val_loss: 0.4528
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4284 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4215 - val_accuracy: 0.8117 - val_loss: 0.4626
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4193 - val_accuracy: 0.7857 - val_loss: 0.4752
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4165 - val_accuracy: 0.7857 - val_loss: 0.4613
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4078 - val_accuracy: 0.7727 - val_loss: 0.4717
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4041 - val_accuracy: 0.7922 - val_loss: 0.4572
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4026 - val_accuracy: 0.7662 - val_loss: 0.4825
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4021 - val_accuracy: 0.8052 - val_loss: 0.4543
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3935 - val_accuracy: 0.8117 - val_loss: 0.4666
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3904 - val_accuracy: 0.7987 - val_loss: 0.4817
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3867 - val_accuracy: 0.7987 - val_loss: 0.4814
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3814 - val_accuracy: 0.7857 - val_loss: 0.4777
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3798 - val_accuracy: 0.7922 - val_loss: 0.4769
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3789 - val_accuracy: 0.7987 - val_loss: 0.4795
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8355 - loss: 0.3742 - val_accuracy: 0.8052 - val_loss: 0.4811
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8339 - loss: 0.3657 - val_accuracy: 0.7987 - val_loss: 0.4811
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8420 - loss: 0.3617 - val_accuracy: 0.7727 - val_loss: 0.4917
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8371 - loss: 0.3578 - val_accuracy: 0.7987 - val_loss: 0.4845
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8534 - loss: 0.3507 - val_accuracy: 0.7662 - val_loss: 0.5295
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8322 - loss: 0.3517 - val_accuracy: 0.7792 - val_loss: 0.5186
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8485 - loss: 0.3501 - val_accuracy: 0.7922 - val_loss: 0.5072
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8567 - loss: 0.3392 - val_accuracy: 0.7857 - val_loss: 0.5108
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8567 - loss: 0.3353 - val_accuracy: 0.7662 - val_loss: 0.5223
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8616 - loss: 0.3316 - val_accuracy: 0.7857 - val_loss: 0.5286
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8583 - loss: 0.3330 - val_accuracy: 0.7987 - val_loss: 0.4961
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8616 - loss: 0.3266 - val_accuracy: 0.7922 - val_loss: 0.5100
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8550 - loss: 0.3214 - val_accuracy: 0.8052 - val_loss: 0.5180
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8730 - loss: 0.3139 - val_accuracy: 0.7792 - val_loss: 0.5339
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8681 - loss: 0.3140 - val_accuracy: 0.7922 - val_loss: 0.5166
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8681 - loss: 0.3049 - val_accuracy: 0.7792 - val_loss: 0.5328
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8795 - loss: 0.3015 - val_accuracy: 0.7922 - val_loss: 0.5196
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.2954 - val_accuracy: 0.7792 - val_loss: 0.5411
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8811 - loss: 0.2900 - val_accuracy: 0.7922 - val_loss: 0.5425
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8827 - loss: 0.2858 - val_accuracy: 0.7662 - val_loss: 0.5444
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.2769 - val_accuracy: 0.7597 - val_loss: 0.5894
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.2770 - val_accuracy: 0.8117 - val_loss: 0.5442
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9072 - loss: 0.2697 - val_accuracy: 0.7857 - val_loss: 0.5743
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8990 - loss: 0.2684 - val_accuracy: 0.7857 - val_loss: 0.5744
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.2642 - val_accuracy: 0.7857 - val_loss: 0.5737
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2614 - val_accuracy: 0.7922 - val_loss: 0.5608
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9055 - loss: 0.2531 - val_accuracy: 0.7922 - val_loss: 0.5784
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2537 - val_accuracy: 0.7792 - val_loss: 0.5800
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8958 - loss: 0.2409 - val_accuracy: 0.7078 - val_loss: 0.6801
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9072 - loss: 0.2457 - val_accuracy: 0.7403 - val_loss: 0.6233
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2361 - val_accuracy: 0.7597 - val_loss: 0.6267
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9235 - loss: 0.2293 - val_accuracy: 0.7662 - val_loss: 0.6399
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9169 - loss: 0.2271 - val_accuracy: 0.7532 - val_loss: 0.6341
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9202 - loss: 0.2204 - val_accuracy: 0.7338 - val_loss: 0.6428
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9218 - loss: 0.2180 - val_accuracy: 0.7403 - val_loss: 0.6753
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9202 - loss: 0.2149 - val_accuracy: 0.7532 - val_loss: 0.6498
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9316 - loss: 0.2013 - val_accuracy: 0.7468 - val_loss: 0.6912
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9169 - loss: 0.2113 - val_accuracy: 0.7597 - val_loss: 0.6759
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9349 - loss: 0.2033 - val_accuracy: 0.7208 - val_loss: 0.7077
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9316 - loss: 0.1936 - val_accuracy: 0.7338 - val_loss: 0.6872
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9316 - loss: 0.1926 - val_accuracy: 0.7273 - val_loss: 0.7260
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9365 - loss: 0.1843 - val_accuracy: 0.7273 - val_loss: 0.7277
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9349 - loss: 0.1848 - val_accuracy: 0.7597 - val_loss: 0.6914
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9414 - loss: 0.1751 - val_accuracy: 0.7338 - val_loss: 0.8081
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9349 - loss: 0.1796 - val_accuracy: 0.7143 - val_loss: 0.7340
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9446 - loss: 0.1715 - val_accuracy: 0.7338 - val_loss: 0.7219
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9430 - loss: 0.1651 - val_accuracy: 0.7338 - val_loss: 0.7939
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9446 - loss: 0.1649 - val_accuracy: 0.7532 - val_loss: 0.7924
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9511 - loss: 0.1627 - val_accuracy: 0.7532 - val_loss: 0.7469
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9544 - loss: 0.1483 - val_accuracy: 0.6948 - val_loss: 0.8281
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9495 - loss: 0.1503 - val_accuracy: 0.7208 - val_loss: 0.8170
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9528 - loss: 0.1491 - val_accuracy: 0.7143 - val_loss: 0.8229
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9577 - loss: 0.1442 - val_accuracy: 0.7208 - val_loss: 0.8427
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9479 - loss: 0.1474 - val_accuracy: 0.7143 - val_loss: 0.8306
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9593 - loss: 0.1335 - val_accuracy: 0.7078 - val_loss: 0.9126
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9560 - loss: 0.1326 - val_accuracy: 0.7208 - val_loss: 0.8921
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9658 - loss: 0.1247 - val_accuracy: 0.6883 - val_loss: 0.9077
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9577 - loss: 0.1302 - val_accuracy: 0.6948 - val_loss: 0.9606
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9674 - loss: 0.1195 - val_accuracy: 0.7013 - val_loss: 0.9919
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9577 - loss: 0.1233 - val_accuracy: 0.6623 - val_loss: 0.9858
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9707 - loss: 0.1071 - val_accuracy: 0.7338 - val_loss: 0.9681
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9625 - loss: 0.1087 - val_accuracy: 0.7143 - val_loss: 0.9457
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9609 - loss: 0.1174 - val_accuracy: 0.7273 - val_loss: 0.9555
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9788 - loss: 0.0996 - val_accuracy: 0.7013 - val_loss: 1.0899
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9625 - loss: 0.1023 - val_accuracy: 0.7273 - val_loss: 1.1485
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9756 - loss: 0.1021 - val_accuracy: 0.7792 - val_loss: 0.9721
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9723 - loss: 0.0930 - val_accuracy: 0.6883 - val_loss: 1.2117
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9625 - loss: 0.0975 - val_accuracy: 0.6753 - val_loss: 1.0943
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9723 - loss: 0.0952 - val_accuracy: 0.7273 - val_loss: 1.0870
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9772 - loss: 0.0959 - val_accuracy: 0.7078 - val_loss: 1.0941
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0865 - val_accuracy: 0.7208 - val_loss: 1.2407
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9739 - loss: 0.0808 - val_accuracy: 0.6883 - val_loss: 1.1466
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9723 - loss: 0.0902 - val_accuracy: 0.6818 - val_loss: 1.1584
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.9870 - loss: 0.0747 - val_accuracy: 0.7208 - val_loss: 1.2291
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0868 - val_accuracy: 0.6883 - val_loss: 1.1406

In [44]:
## Multiple things together

In [52]:
def build_model(hp):

    model = Sequential()
    counter = 0

    for i in range(
        hp.Int('num_layers', min_value=1, max_value=10)
    ):

        if counter == 0:

            model.add(
                Dense(
                    hp.Int(
                        'units' + str(i),
                        min_value=8,
                        max_value=128,
                        step=8
                    ),
                    activation=hp.Choice(
                        'activation' + str(i),
                        values=['relu', 'tanh', 'sigmoid']
                    ),
                    input_dim=8
                )
            )
            model.add(Dropout(hp.Choice('Dropout'+ str(i), values= [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
        else:

            model.add(
                Dense(
                    hp.Int(
                        'units' + str(i),
                        min_value=8,
                        max_value=128,
                        step=8
                    ),
                    activation=hp.Choice(
                        'activation' + str(i),
                        values=['relu', 'tanh', 'sigmoid']
                    )
                )
            )
            model.add(Dropout(hp.Choice('Dropout'+ str(i), values= [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

        counter += 1

    model.add(Dense(1, activation='sigmoid'))
    model.compile(
        optimizer=hp.Choice(
            'optimizer',
            values=['rmsprop', 'adam', 'sgd', 'nadam', 'adadelta']
        ),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [58]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='my_dir',
    project_name='diabetes_tuning_new'
)

In [59]:
tuner.search(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.6428571343421936
Total elapsed time: 00h 00m 23s

In [60]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 9,
 'units0': 48,
 'activation0': 'tanh',
 'Dropout0': 0.2,
 'optimizer': 'sgd',
 'units1': 8,
 'activation1': 'relu',
 'Dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'Dropout2': 0.1,
 'units3': 8,
 'activation3': 'relu',
 'Dropout3': 0.1,
 'units4': 8,
 'activation4': 'relu',
 'Dropout4': 0.1,
 'units5': 8,
 'activation5': 'relu',
 'Dropout5': 0.1,
 'units6': 8,
 'activation6': 'relu',
 'Dropout6': 0.1,
 'units7': 8,
 'activation7': 'relu',
 'Dropout7': 0.1,
 'units8': 8,
 'activation8': 'relu',
 'Dropout8': 0.1}

In [61]:
model = tuner.get_best_models(num_models = 1)[0]

In [62]:
model.fit(X_train,y_train,epochs = 200,initial_epoch= 6,validation_data = (X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.6531 - loss: 0.6786 - val_accuracy: 0.6429 - val_loss: 0.6765
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6717 - val_accuracy: 0.6429 - val_loss: 0.6696
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.6670 - val_accuracy: 0.6429 - val_loss: 0.6647
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6630 - val_accuracy: 0.6429 - val_loss: 0.6603
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6571 - val_accuracy: 0.6429 - val_loss: 0.6566
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6526 - val_accuracy: 0.6429 - val_loss: 0.6534
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6515 - val_accuracy: 0.6429 - val_loss: 0.6510
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6482 - val_accuracy: 0.6429 - val_loss: 0.6494
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6495 - val_accuracy: 0.6429 - val_loss: 0.6482
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6475 - val_accuracy: 0.6429 - val_loss: 0.6472
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.6462 - val_accuracy: 0.6429 - val_loss: 0.6464
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6456 - val_accuracy: 0.6429 - val_loss: 0.6456
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6456 - val_accuracy: 0.6429 - val_loss: 0.6450
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6448 - val_accuracy: 0.6429 - val_loss: 0.6442
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6428 - val_accuracy: 0.6429 - val_loss: 0.6438
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6443 - val_accuracy: 0.6429 - val_loss: 0.6430
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6423 - val_accuracy: 0.6429 - val_loss: 0.6424
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6468 - val_accuracy: 0.6429 - val_loss: 0.6418
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6414 - val_accuracy: 0.6429 - val_loss: 0.6412
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6396 - val_accuracy: 0.6429 - val_loss: 0.6405
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6403 - val_accuracy: 0.6429 - val_loss: 0.6399
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6418 - val_accuracy: 0.6429 - val_loss: 0.6393
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6379 - val_accuracy: 0.6429 - val_loss: 0.6385
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6371 - val_accuracy: 0.6429 - val_loss: 0.6377
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6446 - val_accuracy: 0.6429 - val_loss: 0.6371
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6418 - val_accuracy: 0.6429 - val_loss: 0.6366
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6378 - val_accuracy: 0.6429 - val_loss: 0.6359
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6386 - val_accuracy: 0.6429 - val_loss: 0.6351
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6386 - val_accuracy: 0.6429 - val_loss: 0.6342
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6371 - val_accuracy: 0.6429 - val_loss: 0.6333
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.6344 - val_accuracy: 0.6429 - val_loss: 0.6322
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.6385 - val_accuracy: 0.6429 - val_loss: 0.6315
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6308 - val_accuracy: 0.6429 - val_loss: 0.6301
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6387 - val_accuracy: 0.6429 - val_loss: 0.6295
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6334 - val_accuracy: 0.6429 - val_loss: 0.6285
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6329 - val_accuracy: 0.6429 - val_loss: 0.6274
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6315 - val_accuracy: 0.6429 - val_loss: 0.6263
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6327 - val_accuracy: 0.6429 - val_loss: 0.6250
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6315 - val_accuracy: 0.6429 - val_loss: 0.6236
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.6277 - val_accuracy: 0.6429 - val_loss: 0.6221
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.6227 - val_accuracy: 0.6429 - val_loss: 0.6203
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6268 - val_accuracy: 0.6429 - val_loss: 0.6191
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6275 - val_accuracy: 0.6429 - val_loss: 0.6169
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6267 - val_accuracy: 0.6429 - val_loss: 0.6147
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6147 - val_accuracy: 0.6429 - val_loss: 0.6122
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6228 - val_accuracy: 0.6429 - val_loss: 0.6099
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6231 - val_accuracy: 0.6429 - val_loss: 0.6085
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6199 - val_accuracy: 0.6429 - val_loss: 0.6068
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6181 - val_accuracy: 0.6429 - val_loss: 0.6047
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6173 - val_accuracy: 0.6429 - val_loss: 0.6018
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6099 - val_accuracy: 0.6429 - val_loss: 0.5990
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6086 - val_accuracy: 0.6429 - val_loss: 0.5968
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6150 - val_accuracy: 0.6429 - val_loss: 0.5946
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6531 - loss: 0.6141 - val_accuracy: 0.6429 - val_loss: 0.5918
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6110 - val_accuracy: 0.6429 - val_loss: 0.5895
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6531 - loss: 0.6134 - val_accuracy: 0.6429 - val_loss: 0.5876
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6080 - val_accuracy: 0.6429 - val_loss: 0.5839
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6070 - val_accuracy: 0.6429 - val_loss: 0.5806
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6059 - val_accuracy: 0.6429 - val_loss: 0.5778
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6531 - loss: 0.5955 - val_accuracy: 0.6429 - val_loss: 0.5744
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.5983 - val_accuracy: 0.6429 - val_loss: 0.5729
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6531 - loss: 0.5969 - val_accuracy: 0.6429 - val_loss: 0.5696
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6531 - loss: 0.5911 - val_accuracy: 0.6429 - val_loss: 0.5661
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.5964 - val_accuracy: 0.6429 - val_loss: 0.5638
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5875 - val_accuracy: 0.6429 - val_loss: 0.5583
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5787 - val_accuracy: 0.6429 - val_loss: 0.5544
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5922 - val_accuracy: 0.6429 - val_loss: 0.5526
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5925 - val_accuracy: 0.6429 - val_loss: 0.5492
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5870 - val_accuracy: 0.6429 - val_loss: 0.5500
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5821 - val_accuracy: 0.6429 - val_loss: 0.5462
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5782 - val_accuracy: 0.6429 - val_loss: 0.5422
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.5593 - val_accuracy: 0.6429 - val_loss: 0.5370
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5714 - val_accuracy: 0.6429 - val_loss: 0.5349
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5864 - val_accuracy: 0.6429 - val_loss: 0.5324
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.5719 - val_accuracy: 0.6429 - val_loss: 0.5300
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5694 - val_accuracy: 0.6429 - val_loss: 0.5288
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5716 - val_accuracy: 0.6429 - val_loss: 0.5273
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5539 - val_accuracy: 0.6429 - val_loss: 0.5261
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5664 - val_accuracy: 0.6429 - val_loss: 0.5238
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6547 - loss: 0.5635 - val_accuracy: 0.6429 - val_loss: 0.5264
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.5572 - val_accuracy: 0.6429 - val_loss: 0.5210
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.5676 - val_accuracy: 0.6429 - val_loss: 0.5215
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5537 - val_accuracy: 0.6429 - val_loss: 0.5169
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.5728 - val_accuracy: 0.6429 - val_loss: 0.5172
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.5590 - val_accuracy: 0.6429 - val_loss: 0.5180
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5566 - val_accuracy: 0.6429 - val_loss: 0.5168
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5612 - val_accuracy: 0.6429 - val_loss: 0.5174
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5533 - val_accuracy: 0.6429 - val_loss: 0.5152
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5643 - val_accuracy: 0.6429 - val_loss: 0.5179
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5497 - val_accuracy: 0.6429 - val_loss: 0.5172
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5457 - val_accuracy: 0.6429 - val_loss: 0.5171
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5707 - val_accuracy: 0.6429 - val_loss: 0.5178
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5403 - val_accuracy: 0.6429 - val_loss: 0.5164
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5386 - val_accuracy: 0.6429 - val_loss: 0.5186
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.5548 - val_accuracy: 0.6429 - val_loss: 0.5183
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5542 - val_accuracy: 0.6429 - val_loss: 0.5173
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5825 - val_accuracy: 0.6429 - val_loss: 0.5246
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.5741 - val_accuracy: 0.6429 - val_loss: 0.5243
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6515 - loss: 0.5533 - val_accuracy: 0.6429 - val_loss: 0.5212
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.5523 - val_accuracy: 0.6429 - val_loss: 0.5216
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.5558 - val_accuracy: 0.6429 - val_loss: 0.5201
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5530 - val_accuracy: 0.6429 - val_loss: 0.5196
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5539 - val_accuracy: 0.6429 - val_loss: 0.5209
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6515 - loss: 0.5685 - val_accuracy: 0.6429 - val_loss: 0.5247
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.5557 - val_accuracy: 0.6429 - val_loss: 0.5259
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6515 - loss: 0.5415 - val_accuracy: 0.6429 - val_loss: 0.5224
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.5701 - val_accuracy: 0.6429 - val_loss: 0.5278
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.5697 - val_accuracy: 0.6429 - val_loss: 0.5273
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5474 - val_accuracy: 0.6429 - val_loss: 0.5242
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6466 - loss: 0.5539 - val_accuracy: 0.6429 - val_loss: 0.5240
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.5376 - val_accuracy: 0.6429 - val_loss: 0.5244
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6612 - loss: 0.5580 - val_accuracy: 0.6429 - val_loss: 0.5212
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6433 - loss: 0.5432 - val_accuracy: 0.6429 - val_loss: 0.5197
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.5613 - val_accuracy: 0.6429 - val_loss: 0.5187
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.5598 - val_accuracy: 0.6429 - val_loss: 0.5193
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6743 - loss: 0.5536 - val_accuracy: 0.6688 - val_loss: 0.5184
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6645 - loss: 0.5540 - val_accuracy: 0.7727 - val_loss: 0.5189
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6694 - loss: 0.5608 - val_accuracy: 0.7597 - val_loss: 0.5196
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6596 - loss: 0.5548 - val_accuracy: 0.7792 - val_loss: 0.5208
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6759 - loss: 0.5564 - val_accuracy: 0.7662 - val_loss: 0.5212
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.5411 - val_accuracy: 0.7727 - val_loss: 0.5236
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6629 - loss: 0.5519 - val_accuracy: 0.7662 - val_loss: 0.5212
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.5411 - val_accuracy: 0.7662 - val_loss: 0.5192
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.5447 - val_accuracy: 0.7727 - val_loss: 0.5207
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6906 - loss: 0.5612 - val_accuracy: 0.7662 - val_loss: 0.5216
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.5438 - val_accuracy: 0.7727 - val_loss: 0.5214
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.5614 - val_accuracy: 0.7662 - val_loss: 0.5235
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6987 - loss: 0.5347 - val_accuracy: 0.7662 - val_loss: 0.5203
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6710 - loss: 0.5575 - val_accuracy: 0.7662 - val_loss: 0.5198
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6629 - loss: 0.5553 - val_accuracy: 0.7662 - val_loss: 0.5191
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6824 - loss: 0.5351 - val_accuracy: 0.7532 - val_loss: 0.5182
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6906 - loss: 0.5492 - val_accuracy: 0.7597 - val_loss: 0.5170
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7085 - loss: 0.5357 - val_accuracy: 0.7597 - val_loss: 0.5155
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.5211 - val_accuracy: 0.7597 - val_loss: 0.5168
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5227 - val_accuracy: 0.7597 - val_loss: 0.5189
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6824 - loss: 0.5471 - val_accuracy: 0.7857 - val_loss: 0.5223
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6906 - loss: 0.5432 - val_accuracy: 0.7727 - val_loss: 0.5233
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6857 - loss: 0.5390 - val_accuracy: 0.7857 - val_loss: 0.5216
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7134 - loss: 0.5621 - val_accuracy: 0.7922 - val_loss: 0.5223
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7052 - loss: 0.5435 - val_accuracy: 0.7987 - val_loss: 0.5212
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6954 - loss: 0.5386 - val_accuracy: 0.7857 - val_loss: 0.5205
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6873 - loss: 0.5238 - val_accuracy: 0.7922 - val_loss: 0.5199
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7248 - loss: 0.5228 - val_accuracy: 0.7792 - val_loss: 0.5199
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7085 - loss: 0.5161 - val_accuracy: 0.7987 - val_loss: 0.5197
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7231 - loss: 0.5407 - val_accuracy: 0.7987 - val_loss: 0.5200
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7020 - loss: 0.5394 - val_accuracy: 0.7857 - val_loss: 0.5191
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7036 - loss: 0.5651 - val_accuracy: 0.8052 - val_loss: 0.5208
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7020 - loss: 0.5443 - val_accuracy: 0.7922 - val_loss: 0.5220
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6906 - loss: 0.5411 - val_accuracy: 0.8052 - val_loss: 0.5229
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5409 - val_accuracy: 0.7987 - val_loss: 0.5218
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5416 - val_accuracy: 0.7922 - val_loss: 0.5248
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.5396 - val_accuracy: 0.7857 - val_loss: 0.5265
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 0.5341 - val_accuracy: 0.7987 - val_loss: 0.5237
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5269 - val_accuracy: 0.7857 - val_loss: 0.5257
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.5281 - val_accuracy: 0.7857 - val_loss: 0.5253
Epoch 162/200